INSERT INTO Perguntas (dificuldade, texto) VALUES
('easy', 'Qual é a principal fonte de água potável para a maioria das pessoas?'),
('easy', 'O que é um vazamento de água?'),
('easy', 'O que podemos fazer para ajudar a conservar a água em nossa comunidade?'),
('easy', 'Qual é uma forma de reutilizar a água em casa?'),
('easy', 'O que é a captação de água da chuva?'),
('easy', 'Como a poluição da água afeta os animais aquáticos?'),
('easy', 'Qual é a importância da água subterrânea?'),
('easy', 'O que é reciclagem?'),
('easy', 'Qual é um exemplo de material que pode ser reciclado?'),
('easy', 'O que significa a seta de reciclagem encontrada em muitos produtos?'),
('easy', 'O que devemos fazer antes de colocar um item de plástico para reciclar?'),
('easy', 'Qual é a importância da reciclagem para o meio ambiente?'),
('easy', 'Qual é a finalidade da reciclagem de papel?'),
('easy', 'O que são os 3Rs da sustentabilidade?'),
('easy', 'Por que a reciclagem é importante para economizar recursos naturais?'),
('easy', 'Qual é o objetivo da reciclagem de alumínio?'),
('easy', 'Qual é o impacto da reciclagem na redução das emissões de gases de efeito estufa?'),
('easy', 'O que é um aterro sanitário?'),
('easy', 'Qual é o problema comum associado ao descarte inadequado de resíduos plásticos nos oceanos?'),
('easy', 'O que é lixo eletrônico?'),
('easy', 'Qual é o impacto da queima de resíduos sólidos a céu aberto na qualidade do ar?'),
('easy', 'Qual é o impacto da disposição inadequada de resíduos perigosos?'),
('easy', 'O que são resíduos orgânicos?'),
('easy', 'O que é descarte irregular de resíduos?'),
('easy', 'O que é a incineração de resíduos?'),
('easy', 'O que é um resíduo tóxico?'),
('easy', 'Como podemos reduzir a quantidade de resíduos produzidos?'),
('easy', 'O que é o descarte de resíduos radioativos?'),
('easy', 'Qual é a ideia por trás de "reduzir, reutilizar, reciclar"?'),
('easy', 'Por que a economia circular é importante para o planeta?'),
('easy', 'Como a economia circular pode nos ajudar a ter um mundo mais limpo?'),
('easy', 'O que são "produtos duráveis" na economia circular?'),
('easy', 'Como a economia circular pode nos ajudar a economizar dinheiro?'),
('easy', 'Como a reciclagem ajuda na economia circular?'),
('easy', 'O que é "logística circular" na economia circular?'),
('easy', 'O que é uma "oficina de conserto" na economia circular?'),
('easy', 'O que é "remanufatura"?'),
('easy', 'Como podemos ajudar a promover a economia circular em casa?'),
('easy', 'Por que devemos cuidar dos recursos naturais na economia circular?'),
('easy', 'Como a economia circular pode tornar o mundo um lugar melhor?');



INSERT INTO Perguntas (texto, dificuldade)
VALUES
  ('Qual é a principal fonte de água potável para a maioria das pessoas?', 'medium'),
  ('O que é um vazamento de água?', 'medium'),
  ('O que podemos fazer para ajudar a conservar a água em nossa comunidade?', 'medium'),
  ('Qual é uma forma de reutilizar a água em casa?', 'medium'),
  ('O que é a captação de água da chuva?', 'medium'),
  ('Como a poluição da água afeta os animais aquáticos?', 'medium'),
  ('Qual é a importância da água subterrânea?', 'medium'),
  ('O que é reciclagem?', 'medium'),
  ('Qual é um exemplo de material que pode ser reciclado?', 'medium'),
  ('O que significa a seta de reciclagem encontrada em muitos produtos?', 'medium'),
  ('O que devemos fazer antes de colocar um item de plástico para reciclar?', 'medium'),
  ('Qual é a importância da reciclagem para o meio ambiente?', 'medium'),
  ('Qual é a finalidade da reciclagem de papel?', 'medium'),
  ('O que são os 3Rs da sustentabilidade?', 'medium'),
  ('Por que a reciclagem é importante para economizar recursos naturais?', 'medium'),
  ('Qual é o objetivo da reciclagem de alumínio?', 'medium'),
  ('Qual é o impacto da reciclagem na redução das emissões de gases de efeito estufa?', 'medium'),
  ('O que é um aterro sanitário?', 'medium'),
  ('Qual é o problema comum associado ao descarte inadequado de resíduos plásticos nos oceanos?', 'medium'),
  ('O que é lixo eletrônico?', 'medium'),
  ('Qual é o impacto da queima de resíduos sólidos a céu aberto na qualidade do ar?', 'medium'),
  ('Qual é o impacto da disposição inadequada de resíduos perigosos?', 'medium'),
  ('O que são resíduos orgânicos?', 'medium'),
  ('O que é descarte irregular de resíduos?', 'medium'),
  ('O que é a incineração de resíduos?', 'medium'),
  ('O que é um resíduo tóxico?', 'medium'),
  ('Como podemos reduzir a quantidade de resíduos produzidos?', 'medium'),
  ('O que é o descarte de resíduos radioativos?', 'medium'),
  ('Qual é a ideia por trás de reduzir, reutilizar e reciclar?', 'medium'),
  ('Por que a economia circular é importante para o planeta?', 'medium'),
  ('Como a economia circular pode nos ajudar a ter um mundo mais limpo?', 'medium'),
  ('O que são produtos duráveis na economia circular?', 'medium'),
  ('Como a economia circular pode nos ajudar a economizar dinheiro?', 'medium'),
  ('Como a reciclagem ajuda na economia circular?', 'medium'),
  ('O que é logística circular na economia circular?', 'medium'),
  ('O que é uma oficina de conserto na economia circular?', 'medium'),
  ('O que é remanufatura?', 'medium'),
  ('Como podemos ajudar a promover a economia circular em casa?', 'medium'),
  ('Por que devemos cuidar dos recursos naturais na economia circular?', 'medium'),
  ('Como a economia circular pode tornar o mundo um lugar melhor?', 'medium'),
  ('O que é um exemplo de energia renovável?', 'medium'),
  ('O que é um exemplo de energia não renovável?', 'medium'),
  ('O que é um standby em aparelhos eletrônicos?', 'medium'),
  ('Como podemos economizar energia ao usar o computador?', 'medium'),
  ('O que é um termostato em um aparelho de ar condicionado?', 'medium'),
  ('Como podemos economizar energia ao lavar roupas?', 'medium'),
  ('O que é energia eólica?', 'medium'),
  ('O que é um temporizador em um aparelho eletrônico?', 'medium'),
  ('O que é energia hidrelétrica?', 'medium'),
  ('Como podemos economizar energia ao usar o ar condicionado?', 'medium'),
  ('Qual é uma boa maneira de ter uma alimentação saudável?', 'medium'),
  ('O que são alimentos processados?', 'medium'),
  ('O que é uma porção de comida?', 'medium'),
  ('Quais são os grupos de alimentos que devemos incluir em nossa alimentação?', 'medium'),
  ('O que é uma dieta balanceada?', 'medium'),
  ('O que é fibra alimentar?', 'medium'),
  ('Por que devemos evitar o consumo excessivo de açúcar?', 'medium'),
  ('O que é uma refeição equilibrada?', 'medium'),
  ('O que é um nutriente?', 'medium'),
  ('Como a alimentação saudável pode ajudar no crescimento e desenvolvimento?', 'medium'),
  ('O que é um alimento integral?', 'medium'),
  ('Como podemos fazer escolhas alimentares saudáveis ao comer fora de casa?', 'medium'),
  ('Qual é a relação entre alimentação saudável e energia?', 'medium'),
  ('Por que é importante evitar o consumo excessivo de alimentos gordurosos?', 'medium'),
  ('O que são energias renováveis?', 'medium'),
  ('Qual é uma fonte de energia renovável que vem do sol?', 'medium'),
  ('O que são painéis solares?', 'medium'),
  ('Como a energia do vento é capturada?', 'medium'),
  ('O que é uma usina hidrelétrica?','medium'),
  ('O que é energia geotérmica?','medium'),
  ('Como as energias renováveis ajudam a proteger o meio ambiente?','medium'),
  ('Qual é uma forma de transporte sustentável?','medium'),
  ('Como andar de bicicleta pode ser uma forma sustentável de locomoção?','medium'),
  ('O que é carona solidária?','medium'),
  ('Por que é importante usar o transporte público?','medium'),
  ('O que é um veículo elétrico?','medium'),
  ('O que é compartilhamento de carro?','medium'),
  ('Como o compartilhamento de carro pode ser uma forma de mobilidade sustentável?','medium'),
  ('Qual é a importância de usar meios de transporte mais sustentáveis, como caminhar e andar de bicicleta?','medium'),
  ('O que é um sistema de transporte público?','medium'),
  ('Qual é a importância de planejar viagens e rotas de forma eficiente?','medium'),
  ('Por que é importante reduzir o uso de plástico?','medium'),
  ('O que é bioplástico?','medium'),
  ('O que é um plástico de uso único?','medium'),
  ('O que é decomposição?','medium'),
  ('Como a redução do uso de plástico pode ajudar a proteger os animais?','medium'),
  ('O que é um poluente?','medium'),
  ('O que é uma compostagem?','medium'),
  ('Como as embalagens de plástico podem ser reduzidas?','medium'),
  ('Como as crianças podem ajudar na redução do uso de plástico?','medium'),
  ('O que é um recipiente reutilizável?','medium'),
  ('Como o uso de produtos feitos de plástico biodegradável pode ser benéfico?','medium'),
  ('O que é um plástico biodegradável?','medium'),
  ('Como a bicicleta pode ser uma forma sustentável de locomoção?','medium'),
  ('O que é carona solidária?','medium'),
  ('Por que é importante usar o transporte público?','medium'),
  ('O que é um veículo elétrico?','medium'),
  ('Como os veículos elétricos contribuem para a mobilidade sustentável?','medium'),
  ('O que é compartilhamento de carro?','medium'),
  ('O que é um veículo a gás natural?','medium'),
  ('Como os veículos a gás natural podem ser uma opção sustentável?','medium'),
  ('Qual é a importância de usar meios de transporte mais sustentáveis, como caminhar e andar de bicicleta?','medium'),
  ('O que é um sistema de transporte público?','medium'),
  ('Qual é a importância de planejar viagens e rotas de forma eficiente?','medium');

 
 
 INSERT INTO Perguntas (dificuldade, texto)
VALUES
  ('hard', 'Qual é a importância das zonas úmidas para a saúde dos ecossistemas aquáticos?'),
  ('hard', 'Qual é a principal causa da escassez de água em algumas regiões?'),
  ('hard', 'O que é um ''afluentes'' de um rio?'),
  ('hard', 'Como a agricultura pode afetar a qualidade da água dos rios?'),
  ('hard', 'Qual é a importância das árvores perto de corpos d''água?'),
  ('hard', 'Qual é o papel das zonas de recarga em um aquífero?'),
  ('hard', 'O que é uma barragem?'),
  ('hard', 'Como podemos reduzir a poluição da água proveniente de produtos químicos domésticos?'),
  ('hard', 'O que é a compostagem?'),
  ('hard', 'Qual é a melhor opção para lidar com um produto eletrônico antigo?'),
  ('hard', 'O que é upcycling?'),
  ('hard', 'O que são produtos biodegradáveis?'),
  ('hard', 'O que é um resíduo biodegradável?'),
  ('hard', 'O que é compostagem?'),
  ('hard', 'Qual é o papel dos aterros sanitários no gerenciamento de resíduos?'),
  ('hard', 'O que é a logística reversa?'),
  ('hard', 'O que é economia circular?'),
  ('hard', 'O que podemos fazer para ajudar na economia circular?'),
  ('hard', 'Qual é o objetivo da economia circular?'),
  ('hard', 'O que é a ''cascata de uso'' na economia circular?'),
  ('hard', 'O que é um ''ecossistema de economia circular''?'),
  ('hard', 'O que são ''insumos secundários'' na economia circular?'),
  ('hard', 'O que é a ''cadeia de valor'' na economia circular?'),
  ('hard', 'Por que as energias renováveis são importantes?'),
  ('hard', 'Como as ondas do mar podem ser usadas para gerar energia?'),
  ('hard', 'O que são biocombustíveis?'),
  ('hard', 'O que são células solares?'),
  ('hard', 'Como a energia solar pode ser armazenada para ser usada quando o sol não está brilhando?'),
  ('hard', 'O que é biodiesel?'),
  ('hard', 'Como a energia solar é convertida em eletricidade?'),
  ('hard', 'O que é energia maremotriz?'),
  ('hard', 'Como a biomassa pode ser usada para gerar energia?'),
  ('hard', 'O que é uma usina solar?'),
  ('hard', 'O que é uma turbina eólica?'),
  ('hard', 'O que é energia das marés?'),
  ('hard', 'Como as energias renováveis podem contribuir para um futuro mais sustentável?'),
  ('hard', 'O que é mobilidade sustentável?'),
  ('hard', 'Por que a mobilidade sustentável é importante?'),
  ('hard', 'Como os veículos elétricos contribuem para a mobilidade sustentável?'),
  ('hard', 'O que é um veículo a gás natural?'),
  ('hard', 'Como os veículos a gás natural podem ser uma opção sustentável?'),
  ('hard', 'O que é um veículo movido a hidrogênio?'),
  ('hard', 'Como os veículos movidos a hidrogênio podem contribuir para a mobilidade sustentável?'),
  ('hard', 'O que é um ''carro elétrico híbrido''?'),
  ('hard', 'Como os carros elétricos híbridos podem ser uma opção sustentável?'),
  ('hard', 'O que é uma ''pegada de plástico''?'),
  ('hard', 'O que é um ''ativismo ambiental''?'),
  ('hard', 'O que é mobilidade sustentável?'),
  ('hard', 'Por que a mobilidade sustentável é importante?'),
  ('hard', 'Qual é uma forma de transporte sustentável?'),
  ('hard', 'Como o compartilhamento de carro pode ser uma forma de mobilidade sustentável?'),
  ('hard', 'O que é uma ''ativismo ambiental''?'),
  ('hard', 'O que é uma ''pegada de carbono''?');